In [1]:
import pandas as pd
df = pd.read_csv("cleaned_student_dataset.csv")

In [2]:
import sqlite3
conn=sqlite3.connect("students.db")
df.to_sql("students",conn,if_exists="replace",index=False)

1000

In [3]:
query = """
SELECT COUNT(*) AS total_students
FROM students;
"""

pd.read_sql(query, conn)

   total_students
0            1000

In [4]:
query="""
SELECT Gender, COUNT(*) AS total
FROM students
GROUP BY Gender;
"""
pd.read_sql(query,conn)

  Gender  total
0      F    514
1      M    486

In [5]:
query="""
SELECT Course, COUNT(*) AS total_students
FROM students
GROUP BY Course
ORDER BY total_students DESC
LIMIT 1;
"""
pd.read_sql(query,conn)

  Course  total_students
0    BBA             220

In [6]:
query="""
SELECT Year, COUNT(*) AS total_students
FROM students
GROUP BY Year
ORDER BY Year;
"""
pd.read_sql(query,conn)

   Year  total_students
0     1             248
1     2             264
2     3             247
3     4             241

In [7]:
query="""
SELECT City, COUNT(*) AS total_students
FROM students
GROUP BY City
ORDER BY total_students DESC
LIMIT 5;
"""
pd.read_sql(query,conn)

        City  total_students
0  Bengaluru             111
1       Pune             106
2      Kochi             102
3  Hyderabad             102
4    Kolkata             101

In [8]:
query = """
SELECT AVG(
    CAST(strftime('%Y','now') AS INTEGER) - 
    CAST(strftime('%Y', Date_of_Birth) AS INTEGER)
) AS avg_age
FROM students;
"""
pd.read_sql(query,conn)

   avg_age
0   21.517

In [9]:
query="""
SELECT Course, Gender, COUNT(*) AS total
FROM students
GROUP BY Course, Gender
ORDER BY Course;
"""
pd.read_sql(query,conn)

   Course Gender  total
0   B.Com      F    100
1   B.Com      M     92
2    B.Sc      F     97
3    B.Sc      M     97
4  B.Tech      F    106
5  B.Tech      M     90
6      BA      F    112
7      BA      M     86
8     BBA      F     99
9     BBA      M    121